version: "3.8"

services:
  cms_frontend:
    build: .
    restart: always
    ports:
      - "8080:80"   # Пробрасываем порт 80 контейнера на порт 8080 хоста (вы можете изменить порт по своему усмотрению)
